# Generated by Django 3.1.2 on 2020-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_app', '0002_auto_20201015_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betternigeriaregistration',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='betternigeriaregistration',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
