# Generated by Django 3.1.2 on 2020-10-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_app', '0003_auto_20201015_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betternigeriaregistration',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
