# Generated by Django 3.1.2 on 2021-07-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_app', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='08022334455', max_length=11),
            preserve_default=False,
        ),
    ]
